### ISSUE TITLE
Deployment path does not begin with /

### ISSUE THREAD

**Issue by Bluefitdev** [papertank/envoy-deploy#16]
Is anyone having this issue?

It never happened to me prior. I'm using laravel 8, it was fine on 7 before (i also upgraded the dotenv versioning)

```
❯ envoy run init

In Envoyca58753152131a6f645fe0e2e835f55f.php line 31:

  Careful - your deployment path does not begin with /
```

**Comment by davidrushton** [comment]
@Bluefitdev If you're using the .env variable approach, have you set the `DEPLOY_PATH` variable (https://github.com/papertank/envoy-deploy#config) and can you share what you've set that to? 

That exception is thrown by https://github.com/papertank/envoy-deploy/blob/master/Envoy.blade.php#L17 as a little guard to make sure you've set an absolute path to the deploy directory, avoiding it from messing up your folder structure from the SSH user home directory.

**Comment by robertwt7** [comment]
Yeah i know, weirdly it shows me empty path

currently set to

```
DEPLOY_PATH=/var/www/vhosts/example.com/
```

Even when I edit line 17 at Envoy.blade.php to `echo $path`, it returns empty

**Comment by davidrushton** [comment]
Ah right. I've also reproduced this on a fresh L8 project using a Homestead VM. Looking into a fix - let me know if you get there first...

**Comment by davidrushton** [comment]
Got it and added a PR - #17 . Would you be able to try those changes on your end and confirm that works okay now on Laravel 8? Thanks.

**Comment by robertwt7** [comment]
Its all working now, thanks mate! Appreciate it. love the work
