### ISSUE TITLE
Storage folder does not serve for correct project directory

### ISSUE THREAD

**Issue by iammh93** [papertank/envoy-deploy#21]
Hi guys, after the deployment, i found that my application storage folder pointed to old folder but the current folder already point to latest version.

I got three version of project in root directory

```
--- 20211111060137/ old version 1
--- 20211111064441/ old version 2
--- 20211111072800/ -> current
--- Envoy.blade.php
--- storage/

```

My project showed that current was point to latest project now

```
current -> /home/vagrant/code/homestead/20211111072800/
```

When checking the storage folder. The storage/public was not linked to latest project, instead it link with the old project
Inside my storage/

```
public -> /home/vagrant/code/homestead/20211111060137/storage/app/public/

```

I was expected storage/public should link to the latest project, which is 20211111072800, but now is not, any idea?

**Comment by davidrushton** [comment]
@iammh93 

Can I check what storage folder you are looking inside?

```
ln -s {{ $path }}/storage/public {{ $release }}/public/storage
```

runs for each deployment, which should setup:

`/home/vagrant/code/homestead/20211111060137/public/storage -> /home/vagrant/code/homestead/storage/public`

A future version might simply call `php artisan storage:link`, but in the meantime you're welcome to edit the `deployment_links` and `init` tasks to setup the right symlinks for your project.

**Comment by davidrushton** [comment]
@iammh93 I pushed V4 #22 which now uses Laravel's `php artisan storage:link` command for the storage/app/public directory. There's a few other changes there too (https://github.com/papertank/envoy-deploy/releases/tag/4.0.0)
