### ISSUE TITLE
How do you define multiple environments?

### ISSUE THREAD

**Issue by umbertix** [papertank/envoy-deploy#3]
Hi,

How do you define multiple environments? I managed to just change the current parameters in the envoy.config.php file but I would like to be able to chose the deployment environment obv. and I don't see how you should define it.

Thx

**Comment by davidrushton** [comment]
@umbertix 

The $env variable is tested for existence before being set to a default of "production"

``` php
$env = isset($env) ? $env : "production";
```

This means that you can pass it as a variable to the envoy command, i.e.

```
envoy run deploy --env=development
```

This will use "development" as the $env variable.

**Comment by umbertix** [comment]
Sorry I haven't explained myself clear enough, I was refering to the definition of the environment. If I use the parameter where it would deploy that? Where do you define your production/staging ip's.

Are you supposed to add something along:`@servers(['web-1' => '192.168.1.1', 'web-2' => '192.168.1.2'])`  in the Envoy file?

**Comment by davidrushton** [comment]
Ah, no problem.

We don't usually use this deployment script on non-production servers, as downtime while composer dependencies are installed and migrations are run isn't a problem for us on staging or qa. 

Laravel's envoy command / task runner does support running the same command on multiple servers - see "Multiple Servers" at https://laravel.com/docs/5.2/envoy for more information. 

Hope that helps, and any other suggestions please feel free to submit a PR or issue.
