### ISSUE TITLE
New deploy finished success but changes not seems

### ISSUE THREAD

**Issue by xargr** [papertank/envoy-deploy#6]
After run `envoy run deploy` all tasks run successfully.
New release folder created  and new code seems inside both release folder and current folder.

what kind of permissions must have folders and files 

![2](https://user-images.githubusercontent.com/5754929/28529070-32692ab6-7098-11e7-8205-a2fb1916a4b5.png)

**Comment by davidrushton** [comment]
Hi @xargr 

On my setup, I give the web user read+write permissions to the storage folder, but the `current` and date-based release folders shouldn't need any special permissions.

The `current` folder should be symlinked to the most recent date-based release folder, so it should look as if it contains your code but it is actually just a reference to the most recent release.

Could you check what `ls -la` shows in your root directory?

**Comment by xargr** [comment]
You consider that permissions below is right? 

sudo chown -R :www-data /var/www/html

&&

sudo chmod -R 775 /var/www/storage

**Comment by davidrushton** [comment]
@xargr The storage directory is usually inside Laravel, so if your root was `/var/www/html` then I assume you'd public path would be `/var/www/html/public` and your storage directory would be `/var/www/html/storage`?

My storage directory (and subdirectories) has `drwxrwxr-x` for the folder permissions, and it works fine. Hope that helps.
