### ISSUE TITLE
Laravel 5.5 - Passport

### ISSUE THREAD

**Issue by robsontenorio** [papertank/envoy-deploy#9]
Acording Laravel Passport we should run this in order to generate passport keys on production, once `.gitignore` wont version `*.keys` files.

```
php artisan passport:keys
```

What kind of script change is necessary to handle this?

**Comment by davidrushton** [comment]
Hi @robsontenorio 

I see from the docs that the `php artisan passport:keys` command is supposed to be run once on the server, not each time you deploy changes / new versions. 

You could add it to the `init` task of this deploy script - https://github.com/papertank/envoy-deploy/blob/master/Envoy.blade.php#L27 - but personally I would just SSH in and run that command on the server, once you have created your database and run your migrations for the first time.

Hope that helps.

**Comment by robsontenorio** [comment]
I agree. Thanks !

**Comment by davidrushton** [comment]
No problem 👍
